/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Complejo;
import javax.swing.JOptionPane;

/**
 *
 * @author jramirez25
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtParteI1 = new javax.swing.JTextField();
        txtParteR1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtParteI2 = new javax.swing.JTextField();
        txtParteR2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbOperacion = new javax.swing.JComboBox<String>();
        jLabel12 = new javax.swing.JLabel();
        cmdLimpiar = new javax.swing.JButton();
        cmdCalcular = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtNumeradorParteI = new javax.swing.JTextField();
        txtDenominadorParteI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtNumeradorParteR = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtDenominadorParteR = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txtParteI3 = new javax.swing.JTextField();
        txtParteR3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("OPERACIONES CON NÚMEROS COMPLEJOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel3.setText("i");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 67, 10, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel4.setText("Z1 = ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 63, -1, -1));

        txtParteI1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(txtParteI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 60, 25));

        txtParteR1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(txtParteR1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, 25));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel5.setText("+");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 63, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel6.setText("i");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 117, 10, -1));

        txtParteI2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(txtParteI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 60, 25));

        txtParteR2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jPanel1.add(txtParteR2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 60, 25));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel7.setText("+");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 113, -1, -1));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel8.setText("Z2 = ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 113, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel9.setText("Z1");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        cmbOperacion.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cmbOperacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-", "x", "÷" }));
        jPanel1.add(cmbOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 160, 40, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setText("Z2");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 160, -1, -1));

        cmdLimpiar.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, 30));

        cmdCalcular.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resulado División:"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel10.setText("i");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 10, -1));

        txtNumeradorParteI.setEditable(false);
        jPanel2.add(txtNumeradorParteI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 60, 25));

        txtDenominadorParteI.setEditable(false);
        jPanel2.add(txtDenominadorParteI, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 60, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("+");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 60, 10));

        txtNumeradorParteR.setEditable(false);
        jPanel2.add(txtNumeradorParteR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 25));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 60, 10));

        txtDenominadorParteR.setEditable(false);
        txtDenominadorParteR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDenominadorParteRActionPerformed(evt);
            }
        });
        jPanel2.add(txtDenominadorParteR, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, 25));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resulado:"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jLabel13.setText("i");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 10, -1));

        txtParteI3.setEditable(false);
        jPanel3.add(txtParteI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 60, 25));

        txtParteR3.setEditable(false);
        jPanel3.add(txtParteR3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 60, 25));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("+");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(312, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        // TODO add your handling code here:
        txtParteR1.setText("");
        txtParteI1.setText("");
        txtParteR2.setText("");
        txtParteI2.setText("");
        txtParteR3.setText("");
        txtParteI3.setText("");
        txtNumeradorParteR.setText("");
        txtDenominadorParteR.setText("");
        txtNumeradorParteI.setText("");
        txtDenominadorParteI.setText("");
        txtParteR1.requestFocusInWindow();
        cmbOperacion.setSelectedIndex(0);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        // TODO add your handling code here:
        try {
                int op;
                int r1, i1, r2, i2, aux;
                Complejo z1, z2, z3;
                
                op = cmbOperacion.getSelectedIndex();
                r1 = Integer.parseInt(txtParteR1.getText());
                i1 = Integer.parseInt(txtParteI1.getText());
                r2 = Integer.parseInt(txtParteR2.getText());
                i2 = Integer.parseInt(txtParteI2.getText());
           
                z1 = new Complejo(r1, i1);
                z2 = new Complejo(r2, i2);
                switch (op) {
                    case 0:
                        z3 = z1.sumar(z2);
                        txtParteR3.setText(""+z3.getParteR());
                        txtParteI3.setText(""+z3.getParteI());
                        break;
                    case 1:
                        z3 = z1.restar(z2);
                        txtParteR3.setText(""+ z3.getParteR());
                        txtParteI3.setText(""+ z3.getParteI());
                        break;
                    case 2:
                        z3 = z1.multiplicar(z2);
                        txtParteR3.setText(""+ z3.getParteR());
                        txtParteI3.setText(""+ z3.getParteI());
                        break;
                    case 3:
                        z3 = z1.dividir(z2);
                        txtParteR3.setText("");
                        txtParteI3.setText("");
                        aux = (z2.getParteR() * z2.getParteR()) + (z2.getParteI() * z2.getParteI());
                        txtNumeradorParteR.setText(""+ z3.getParteR());
                        txtDenominadorParteR.setText(""+aux);
                        txtNumeradorParteI.setText(""+ z3.getParteI());
                        txtDenominadorParteI.setText(""+aux);
                        break;
                }
            }
            catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Campo(s) inválido(s)", "ERROR", JOptionPane.ERROR_MESSAGE);
                txtParteR1.setText("");
                txtParteI1.setText("");
                txtParteR2.setText("");
                txtParteI2.setText("");
                txtParteR3.setText("");
                txtParteI3.setText("");
                txtNumeradorParteR.setText("");
                txtDenominadorParteR.setText("");
                txtNumeradorParteI.setText("");
                txtDenominadorParteI.setText("");
                txtParteR1.requestFocusInWindow();
                cmbOperacion.setSelectedIndex(0);
            }
    }//GEN-LAST:event_cmdCalcularActionPerformed

    private void txtDenominadorParteRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDenominadorParteRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDenominadorParteRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbOperacion;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtDenominadorParteI;
    private javax.swing.JTextField txtDenominadorParteR;
    private javax.swing.JTextField txtNumeradorParteI;
    private javax.swing.JTextField txtNumeradorParteR;
    private javax.swing.JTextField txtParteI1;
    private javax.swing.JTextField txtParteI2;
    private javax.swing.JTextField txtParteI3;
    private javax.swing.JTextField txtParteR1;
    private javax.swing.JTextField txtParteR2;
    private javax.swing.JTextField txtParteR3;
    // End of variables declaration//GEN-END:variables
}
